dist: 'xenial'
branches:
  except:
  - "/^wip/"
language: node_js
node_js:
- '10'
before_install:
- sudo apt-get update -q -y
- sudo apt-get install -y realpath
script:
- yarn lint
- TZ="America/Los_Angeles" yarn test
after_success: yarn run coverage
